### ISSUE TITLE
GlobalBan Issue

### ISSUE THREAD

**Issue by art1fact** [unturnedROCKS/GlobalBan#3]
So, I still get this error after all of your changes in this plugin:
[Exception] GlobalBan >> Exception in Execute: System.NullReferenceException: Object reference not set to an instance of an object
at unturned.ROCKS.GlobalBan.CommandBan.Execute (Rocket.Unturned.Player.RocketPlayer caller, System.String[] command) [0x00000] in :0

**Comment by fr34kyn01535** [comment]
Have you recreated the config?

**Comment by fr34kyn01535** [comment]
How are you calling the command?

**Comment by art1fact** [comment]
1.) Yes. Everytime when you release update for this plugin I try this.
2.) From console and from game client.

**Comment by art1fact** [comment]
So. This still doesn't work for me

**Comment by art1fact** [comment]
Now it works! Ty
